global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'
    continue: true

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'alerts@example.com'
    send_resolved: true
    
- name: 'slack-critical'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/REPLACE_THIS_WITH_ACTUAL_WEBHOOK_URL'
    channel: '#monitoring-alerts'
    send_resolved: true
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']