version: "3"

tasks:
  run:
    desc: Exécute un agent spécifique
    summary: |
      Exécute un agent MCP spécifique
      
      Exemples:
        - task agents:run -- auto-pr-agent
        - task agents:run -- diff-verifier --file=src/controller/UserController.ts
    cmds:
      - node scripts/agent-runner.js run {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]

  ci-tester:
    desc: Exécute l'agent de test CI
    cmds:
      - node agents/ci-tester.js {{.CLI_ARGS}}

  diff-verifier:
    desc: Vérifie les différences entre les fichiers PHP et leurs versions migrées
    cmds:
      - node agents/diff-verifier.js {{.CLI_ARGS}}

  auto-pr:
    desc: Crée automatiquement des PRs pour les migrations validées
    cmds:
      - node agents/auto-pr-agent.js {{.CLI_ARGS}}

  orchestrator:
    desc: Exécute l'orchestrateur de migration
    cmds:
      - node agents/migration-orchestrator.js {{.CLI_ARGS}}

  bullmq-orchestrator:
    desc: Démarre l'orchestrateur de tâches BullMQ
    cmds:
      - node agents/bullmq-orchestrator.js {{.CLI_ARGS}}

  dev-integrator:
    desc: Intègre les changements dans l'environnement de développement
    cmds:
      - node agents/dev-integrator.js {{.CLI_ARGS}}

  dev-linter:
    desc: Exécute le linter sur le code développé
    cmds:
      - node agents/dev-linter.js {{.CLI_ARGS}}

  list:
    desc: Liste tous les agents disponibles
    cmds:
      - node scripts/agent-runner.js list

  status:
    desc: Affiche le statut de tous les agents
    cmds:
      - node scripts/agent-runner.js status