global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX'  # À remplacer avec votre webhook Slack

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'monitoring@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'alertmanager'
    auth_password: 'password'  # À remplacer avec votre mot de passe SMTP
    send_resolved: true

- name: 'slack-critical'
  slack_configs:
  - channel: '#monitoring-alerts'
    send_resolved: true
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    text: >-
      {{ range .Alerts -}}
      *Alerte:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Gravité:* {{ .Labels.severity }}
      {{ if ne .Annotations.runbook_url "" }}*Runbook:* <{{ .Annotations.runbook_url }}|Lien>{{ end }}
      *Détails:*
      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
      {{ end }}
      {{ end }}