name: Documentation CI/CD

on:
  push:
    paths:
      - 'cahier-des-charges/**'
      - 'templates/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'cahier-des-charges/**'
      - 'templates/**'
      - 'scripts/**'
  schedule:
    - cron: '0 2 * * 1'  # Exécution hebdomadaire (lundi 2h00)

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdownlint-cli mdformat-gfm yamllint jsonschema
          
      - name: Validate markdown formatting
        run: |
          mdformat --check cahier-des-charges/
          
      - name: Check for broken links
        run: |
          python scripts/check_internal_links.py
          
      - name: Verify cross-references
        run: |
          python scripts/verify_cross_refs.py
          
      - name: Check terminology consistency
        run: |
          python scripts/check_glossary.py
          
  generate:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mdx_truly_sane_lists
          
      - name: Generate HTML documentation
        run: |
          python generate_cahier_html.py
          
      - name: Generate PDF version
        run: |
          python scripts/generate_pdf.py
          
      - name: Push generated files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
