#!/usr/bin/env node
/**
 * prisma-migration-generator.ts
 *
 * Cet agent génère les commandes Prisma nécessaires pour la migration basée sur
 * le modèle Prisma suggéré et peut déclencher les migrations en fonction des options choisies.
 *
 * Usage: ts-node prisma-migration-generator.ts [options]
 *
 * Options:
 *   --mode=<mode>       Mode de migration (preview, diff, push, migrate)
 *   --schema=<path>     Chemin vers le fichier schema.prisma à utiliser
 *   --from=<path>       Chemin vers le fichier de modèle Prisma suggéré
 *   --to=<path>         Chemin de destination pour l'intégration du schema
 *   --dry-run           Affiche les commandes sans les exécuter
 *   --auto-generate-dto Génère automatiquement les DTOs NestJS
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { program } from 'commander';

// Configuration de la ligne de commande
program
  .version('1.0.0')
  .description('Génère et exécute les commandes Prisma pour la migration')
  .option('--mode <mode>', 'Mode de migration (preview, diff, push, migrate)', 'preview')
  .option(
    '--schema <path>',
    'Chemin vers le fichier schema.prisma à utiliser',
    './prisma/schema.prisma'
  )
  .option(
    '--from <path>',
    'Chemin vers le fichier de modèle Prisma suggéré',
    './reports/latest/prisma_models.suggestion.prisma'
  )
  .option(
    '--to <path>',
    "Chemin de destination pour l'intégration du schema",
    './apps/backend/prisma/schema.prisma'
  )
  .option('--dry-run', 'Affiche les commandes sans les exécuter', false)
  .option('--auto-generate-dto', 'Génère automatiquement les DTOs NestJS', false)
  .parse(process.argv);

const options = program.opts();

// Vérification des chemins
const fromPath = path.resolve(options.from);
const toPath = path.resolve(options.to);
const schemaPath = path.resolve(options.schema);

/**
 * Fonction principale
 */
async function main() {
  try {
    console.log(chalk.blue('🚀 Démarrage du générateur de migration Prisma'));

    // Vérifier que les fichiers existent
    if (!fs.existsSync(fromPath)) {
      console.error(chalk.red(`❌ Erreur: Le fichier ${fromPath} n'existe pas`));
      process.exit(1);
    }

    // En fonction du mode choisi
    switch (options.mode) {
      case 'preview':
        await previewMigration();
        break;
      case 'diff':
        await generateDiff();
        break;
      case 'push':
        await pushSchema();
        break;
      case 'migrate':
        await migrateSchema();
        break;
      default:
        console.error(chalk.red(`❌ Mode non reconnu: ${options.mode}`));
        process.exit(1);
    }

    // Génération de DTOs si demandé
    if (options.autoGenerateDto) {
      await generateDtos();
    }

    console.log(chalk.green('✅ Opération terminée avec succès'));
  } catch (error) {
    console.error(chalk.red(`❌ Erreur: ${error.message}`));
    console.error(error);
    process.exit(1);
  }
}

/**
 * Affiche un aperçu de la migration sans appliquer les changements
 */
async function previewMigration() {
  console.log(chalk.blue("📊 Génération de l'aperçu de la migration..."));

  // Lire le contenu du fichier suggéré
  const suggestedSchema = fs.readFileSync(fromPath, 'utf8');
  console.log(chalk.gray('Schema Prisma suggéré chargé'));

  // Créer une copie temporaire du schéma existant si nécessaire
  let tempSchemaPath = '';
  if (fs.existsSync(schemaPath)) {
    tempSchemaPath = `${schemaPath}.backup`;
    fs.copyFileSync(schemaPath, tempSchemaPath);
    console.log(chalk.gray(`Sauvegarde du schéma existant créée: ${tempSchemaPath}`));
  }

  try {
    // Copier le schéma suggéré vers le schéma cible (temporairement)
    fs.writeFileSync(schemaPath, suggestedSchema);
    console.log(chalk.gray(`Schema temporairement écrit dans: ${schemaPath}`));

    // Exécuter la commande prisma migrate diff
    const command = `npx prisma migrate diff --from-schema-datamodel ${
      tempSchemaPath || 'mysql://url'
    } --to-schema-datamodel ${schemaPath} --pretty`;
    console.log(chalk.blue(`Exécution de: ${command}`));

    if (!options.dryRun) {
      const output = execSync(command).toString();
      console.log(chalk.green('Aperçu de la migration:'));
      console.log(output);
    } else {
      console.log(chalk.yellow('[DRY RUN] La commande aurait été exécutée'));
    }
  } finally {
    // Restaurer le schéma original
    if (tempSchemaPath) {
      fs.copyFileSync(tempSchemaPath, schemaPath);
      fs.unlinkSync(tempSchemaPath);
      console.log(chalk.gray('Schéma original restauré'));
    }
  }
}

/**
 * Génère un diff SQL entre le schéma actuel et le schéma cible
 */
async function generateDiff() {
  console.log(chalk.blue('📝 Génération du diff SQL...'));

  // Copier le schéma suggéré vers la destination souhaitée
  if (options.to !== options.schema) {
    fs.copyFileSync(fromPath, toPath);
    console.log(chalk.gray(`Fichier copié de ${fromPath} vers ${toPath}`));
  }

  // Exécuter la commande prisma migrate diff
  const command = `npx prisma migrate diff --from-schema-datasource ${options.schema} --to-schema-datamodel ${toPath} --script > migration.sql`;
  console.log(chalk.blue(`Exécution de: ${command}`));

  if (!options.dryRun) {
    execSync(command);
    console.log(chalk.green('✅ Fichier migration.sql généré avec succès'));
  } else {
    console.log(chalk.yellow('[DRY RUN] La commande aurait été exécutée'));
  }
}

/**
 * Pousse le schéma directement vers la base de données sans migration
 */
async function pushSchema() {
  console.log(chalk.blue('📤 Push du schéma vers la base de données...'));

  // Copier le schéma suggéré vers la destination souhaitée
  fs.copyFileSync(fromPath, toPath);
  console.log(chalk.gray(`Fichier copié de ${fromPath} vers ${toPath}`));

  // Exécuter la commande prisma db push
  const command = `npx prisma db push --schema=${toPath} --accept-data-loss`;
  console.log(chalk.blue(`Exécution de: ${command}`));

  if (!options.dryRun) {
    const output = execSync(command).toString();
    console.log(output);
    console.log(chalk.green('✅ Schéma poussé avec succès vers la base de données'));
  } else {
    console.log(chalk.yellow('[DRY RUN] La commande aurait été exécutée'));
  }
}

/**
 * Crée une migration nommée et l'applique
 */
async function migrateSchema() {
  console.log(chalk.blue("🔄 Création d'une migration Prisma..."));

  // Copier le schéma suggéré vers la destination souhaitée
  fs.copyFileSync(fromPath, toPath);
  console.log(chalk.gray(`Fichier copié de ${fromPath} vers ${toPath}`));

  // Générer un nom de migration basé sur la date
  const migrationName = `migration_${new Date().toISOString().replace(/[:.]/g, '_').slice(0, 19)}`;

  // Exécuter la commande prisma migrate dev
  const command = `npx prisma migrate dev --schema=${toPath} --name=${migrationName}`;
  console.log(chalk.blue(`Exécution de: ${command}`));

  if (!options.dryRun) {
    const output = execSync(command).toString();
    console.log(output);
    console.log(chalk.green('✅ Migration créée et appliquée avec succès'));
  } else {
    console.log(chalk.yellow('[DRY RUN] La commande aurait été exécutée'));
  }
}

/**
 * Génère les DTOs NestJS à partir du schéma Prisma
 */
async function generateDtos() {
  console.log(chalk.blue('📋 Génération des DTOs NestJS...'));

  // Vérifier si prisma-nestjs-dto est installé
  try {
    execSync('npm list -g prisma-nestjs-dto');
  } catch (error) {
    console.log(chalk.yellow('Installation de prisma-nestjs-dto...'));
    if (!options.dryRun) {
      execSync('npm install -g prisma-nestjs-dto');
    } else {
      console.log(chalk.yellow("[DRY RUN] La commande d'installation aurait été exécutée"));
    }
  }

  // Exécuter la commande de génération de DTOs
  const outputDir = './apps/backend/src/dto';
  const command = `prisma-nestjs-dto generate --input ${toPath} --output ${outputDir}`;
  console.log(chalk.blue(`Exécution de: ${command}`));

  if (!options.dryRun) {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    const output = execSync(command).toString();
    console.log(output);
    console.log(chalk.green(`✅ DTOs générés dans ${outputDir}`));
  } else {
    console.log(chalk.yellow('[DRY RUN] La commande aurait été exécutée'));
  }
}

// Exécuter la fonction principale
main().catch((error) => {
  console.error(chalk.red('Erreur inattendue:'), error);
  process.exit(1);
});
