name: Earthly Builds

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/backend/**'
      - 'apps/mcp-server/**'
      - 'apps/mcp-server-postgres/**'
      - 'packages/**'
      - 'Earthfile'
      - 'docker/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/backend/**'
      - 'apps/mcp-server/**'
      - 'apps/mcp-server-postgres/**'
      - 'packages/**'
      - 'Earthfile'
      - 'docker/**'
  workflow_dispatch:

jobs:
  earthly-build:
    name: Earthly Reproducible Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.7.9
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run CI Pipeline
        run: earthly --ci +ci

      - name: Build Docker Images (on main branch only)
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_TAG: ${{ github.sha }}
        run: |
          earthly --ci --push \
            +docker-backend --DOCKER_TAG=${DOCKER_TAG} \
            +docker-mcp-server --DOCKER_TAG=${DOCKER_TAG} \
            +docker-frontend --DOCKER_TAG=${DOCKER_TAG}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7