name: Validate 3-Layer Agents

on:
  push:
    paths:
      - 'packages/business/**/*-agent.ts'
      - 'packages/coordination/**/*-agent.ts'
      - 'packages/orchestration/**/*-agent.ts'
      - 'packages/business/**/agent/*.ts'
      - 'packages/coordination/**/agent/*.ts'
      - 'packages/orchestration/**/agent/*.ts'
  pull_request:
    paths:
      - 'packages/business/**/*-agent.ts'
      - 'packages/coordination/**/*-agent.ts'
      - 'packages/orchestration/**/*-agent.ts'
      - 'packages/business/**/agent/*.ts'
      - 'packages/coordination/**/agent/*.ts'
      - 'packages/orchestration/**/agent/*.ts'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate agents implementation
        run: node ./tools/ci/validate-3layer-agents.js
        
      - name: Commit changes if needed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: correction automatique des erreurs TypeScript des agents (3-layer)"
          commit_user_name: "3-Layer Auto-Fix Bot"
          commit_user_email: "autofix-bot@example.com"
          file_pattern: 'packages/business/**/*-agent.ts packages/coordination/**/*-agent.ts packages/orchestration/**/*-agent.ts packages/business/**/agent/*.ts packages/coordination/**/agent/*.ts packages/orchestration/**/agent/*.ts'
